# Generated by Django 5.1.6 on 2025-03-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_name',
            field=models.CharField(default='atsuomi', max_length=150),
            preserve_default=False,
        ),
    ]
