# Generated by Django 5.1.6 on 2025-03-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_u_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='user_name',
        ),
    ]
