# Generated by Django 5.1.6 on 2025-03-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
