# Generated by Django 5.1.6 on 2025-03-19 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the theatre.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Theatre',
                'verbose_name_plural': 'Theatres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(help_text='Name of the course or lecture title.', max_length=100)),
                ('start_time', models.DateTimeField(help_text='Start time of the lecture.')),
                ('end_time', models.DateTimeField(help_text='End time of the lecture.')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='booking.theatre')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name or title of the event.', max_length=100)),
                ('start_time', models.DateTimeField(help_text='Booking start time.')),
                ('end_time', models.DateTimeField(help_text='Booking end time.')),
                ('organizer', models.CharField(help_text='Name of the person or organization making the booking.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.theatre')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['start_time'],
            },
        ),
    ]
