# Generated by Django 5.1.6 on 2025-03-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
    ]
