# Generated by Django 5.1.7 on 2025-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_occurrence_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['occurrence_date']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='occurrence_date',
            field=models.DateField(),
        ),
    ]
